# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hTHlrjDvVKcaUZjqwRXWqccEXvUdSeqQ
"""

# Dataset path: /content/drive/MyDrive/dataset

# 1) SETUP & DEPENDENCIES

import os
import cv2
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2) CONFIGURATION
DATASET_PATH = '/content/drive/MyDrive/dataset'
IMG_SIZE = (256, 256)
CLASSES = ['defocused_blurred', 'motion_blurred', 'sharp']

# 3) FEATURE EXTRACTION FUNCTIONS

# 1. Variance of Laplacian (focus measure)
def laplacian_variance(gray):
    return cv2.Laplacian(gray, cv2.CV_64F).var()

#2.Sobel edge strength
def sobel_strength(gray):
    sx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
    sy = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
    return np.mean(np.sqrt(sx**2 + sy**2))

#3.FFT high-frequency energy (motion blur sensitive)
def fft_high_freq_energy(gray):
    f = np.fft.fft2(gray)
    fshift = np.fft.fftshift(f)
    magnitude = np.abs(fshift)

    h, w = gray.shape
    center = (h // 2, w // 2)
    r = 30

    mask = np.ones((h, w), np.uint8)
    cv2.circle(mask, center, r, 0, -1)

    high_freq = magnitude * mask
    return np.mean(high_freq)

# 4. Image entropy
def image_entropy(gray):
    hist = cv2.calcHist([gray], [0], None, [256], [0, 256])
    hist = hist / hist.sum()
    hist = hist[hist > 0]
    return -np.sum(hist * np.log2(hist))


# 4) LOAD DATASET & BUILD FEATURE MATRIX

features = []
labels = []

for label, cls in enumerate(CLASSES):
    folder = os.path.join(DATASET_PATH, cls)
    for img_name in tqdm(os.listdir(folder), desc=f'Processing {cls}'):
        img_path = os.path.join(folder, img_name)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue

        img = cv2.resize(img, IMG_SIZE)

        f1 = laplacian_variance(img)
        f2 = sobel_strength(img)
        f3 = fft_high_freq_energy(img)
        f4 = image_entropy(img)

        features.append([f1, f2, f3, f4])
        labels.append(label)

X = np.array(features)
y = np.array(labels)

print('Feature matrix shape:', X.shape)
# 5) TRAIN / TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 6) MODEL 1: SUPPORT VECTOR MACHINE (SVM)

svm_model = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='rbf', C=10, gamma='scale'))
])

svm_model.fit(X_train, y_train)
svm_preds = svm_model.predict(X_test)

print('--- SVM RESULTS ---')
print('Accuracy:', accuracy_score(y_test, svm_preds))
print(classification_report(y_test, svm_preds, target_names=CLASSES))


# 7) MODEL 2: RANDOM FOREST (COMPARISON)

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    random_state=42
)

rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)

print('--- RANDOM FOREST RESULTS ---')
print('Accuracy:', accuracy_score(y_test, rf_preds))
print(classification_report(y_test, rf_preds, target_names=CLASSES))


# 8) CONFUSION MATRIX


# SVM Confusion Matrix
cm_svm = confusion_matrix(y_test, svm_preds)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm_svm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=CLASSES,
    yticklabels=CLASSES
)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - SVM')
plt.show()

#  Random Forest Confusion Matrix
cm_rf = confusion_matrix(y_test, rf_preds)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm_rf,
    annot=True,
    fmt='d',
    cmap='Greens',
    xticklabels=CLASSES,
    yticklabels=CLASSES
)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Random Forest')
plt.show()


# 9) VISUALIZE SAMPLE BLUR DETECTION RESULTS

# Extract features from a single image
def extract_features_from_image(img_path):
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    img = cv2.resize(img, IMG_SIZE)

    f1 = laplacian_variance(img)
    f2 = sobel_strength(img)
    f3 = fft_high_freq_energy(img)
    f4 = image_entropy(img)

    return np.array([f1, f2, f3, f4]).reshape(1, -1)

# Display random samples with predicted labels
def show_prediction_samples(model, samples_per_class=3):
    plt.figure(figsize=(12, 8))
    plot_idx = 1

    for cls in CLASSES:
        folder = os.path.join(DATASET_PATH, cls)
        images = np.random.choice(os.listdir(folder), samples_per_class, replace=False)

        for img_name in images:
            img_path = os.path.join(folder, img_name)
            img = cv2.imread(img_path)
            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            features = extract_features_from_image(img_path)
            pred_label = model.predict(features)[0]
            pred_name = CLASSES[pred_label]

            plt.subplot(len(CLASSES), samples_per_class, plot_idx)
            plt.imshow(img_rgb)
            plt.title(f"True: {cls}\nPred: {pred_name}")
            plt.axis('off')
            plot_idx += 1

    plt.tight_layout()
    plt.show()

show_prediction_samples(svm_model)